### ISSUE TITLE
Setting a nick does not return the nick saved on the channel

### ISSUE THREAD

**Issue by mathieui** [tigase/tigase-mix#1]
Per https://xmpp.org/extensions/xep-0369.html#usecase-setting-nick, the channel should return the nick in the IQ result, since it may be different than the one sent by the client.

I believe the current wording of the XEP should be edited to a MUST (currently it is "the channel will return the nick that is to be used", which I interpret the same way)

**Comment by hantu85** [comment]
Thank you for reporting that. It should be fixed in the next daily build or when a server will be upgraded.

In the future, could you attach XML parts which you think are wrong? That would help us verifying the issue faster.

**Comment by mathieui** [comment]
Sure! I didn’t have it right now as I saw the issue yesterday, but I will do it for the next ones
